import React, { useEffect, useState } from 'react';
import { AlertOctagon, AlertTriangle, CheckCircle2, Info, RefreshCw, Sparkles } from 'lucide-react';
import { aiService, AiInvoiceReview as Review } from '@/services/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Invoice, formatDateTime } from './invoiceModel';

const RISK_META: Record<Review['riskLevel'], { label: string; className: string; panel: string }> = {
  low: { label: 'Low risk', className: 'bg-emerald-50 text-emerald-700 border-emerald-200', panel: 'border-emerald-200' },
  medium: { label: 'Worth a look', className: 'bg-amber-50 text-amber-800 border-amber-200', panel: 'border-amber-200' },
  high: { label: 'High risk', className: 'bg-red-50 text-red-700 border-red-200', panel: 'border-red-200' },
};

const FLAG_ICON = {
  critical: <AlertOctagon className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />,
  warning: <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />,
  info: <Info className="w-4 h-4 text-sky-600 shrink-0 mt-0.5" />,
};

// On-demand anomaly check by Claude: duplicates, unusual amounts for this vendor, PO / GRN mismatches.
// Advisory only, like the match table: approval stays with a person.
export function AiInvoiceReview({ inv }: { inv: Invoice }) {
  const [review, setReview] = useState<Review | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // A different invoice, or an edit to this one, makes the last answer stale.
  useEffect(() => { setReview(null); setError(null); }, [inv.id, inv.updatedAt]);

  const run = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await aiService.reviewInvoice(inv.id);
      setReview(res.data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not run the AI check');
    } finally {
      setLoading(false);
    }
  };

  const meta = review ? RISK_META[review.riskLevel] : null;

  return (
    <section className="space-y-3">
      <div className="flex items-center justify-between gap-3">
        <h2 className="text-base font-semibold text-foreground flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-primary" /> AI anomaly check
          {meta && <Badge variant="outline" className={meta.className}>{meta.label}</Badge>}
        </h2>
        <Button variant="outline" size="sm" className="gap-1.5" onClick={run} disabled={loading}>
          {review ? <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} /> : <Sparkles className="w-3.5 h-3.5 text-primary" />}
          {loading ? 'Checking…' : review ? 'Check again' : 'Check with AI'}
        </Button>
      </div>

      {!review && !loading && !error && (
        <p className="text-sm text-muted-foreground">
          Claude compares this bill with the PO, the goods receipt and this vendor's earlier invoices, and flags duplicates, unusual amounts and mismatches.
        </p>
      )}
      {loading && !review && (
        <p className="text-sm text-muted-foreground flex items-center gap-2" aria-live="polite">
          <Sparkles className="w-4 h-4 text-primary animate-pulse" /> Checking against the PO, receipt and vendor history…
        </p>
      )}
      {error && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 flex items-start gap-2" role="alert">
          <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" /> {error}
        </div>
      )}

      {review && meta && (
        <div className={`rounded-lg border bg-card p-4 space-y-3 ${meta.panel}`}>
          <p className="text-sm text-foreground">{review.summary}</p>
          {review.flags.length === 0 ? (
            <p className="text-sm text-emerald-700 flex items-center gap-2"><CheckCircle2 className="w-4 h-4" /> Nothing unusual found.</p>
          ) : (
            <ul className="space-y-2">
              {review.flags.map((f, i) => (
                <li key={i} className="flex items-start gap-2 text-sm">
                  {FLAG_ICON[f.severity]}
                  <span><span className="font-medium text-foreground">{f.title}.</span> <span className="text-muted-foreground">{f.detail}</span></span>
                </li>
              ))}
            </ul>
          )}
          <p className="text-sm"><span className="font-medium text-foreground">Suggested next step:</span> <span className="text-muted-foreground">{review.recommendation}</span></p>
          <p className="text-xs text-muted-foreground">Generated by Claude {formatDateTime(review.generatedAt)}. Advisory only; check the flags before acting.</p>
        </div>
      )}
    </section>
  );
}
