import React, { useEffect, useState } from 'react';
import { AlertTriangle, ArrowRight, RefreshCw, Sparkles, TrendingUp } from 'lucide-react';
import { aiService, AiFinanceSummary as Summary } from '@/services/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

function List({ icon, title, items, tone }: { icon: React.ReactNode; title: string; items: string[]; tone: string }) {
  if (!items.length) return null;
  return (
    <div className="space-y-2">
      <h3 className={`text-xs font-semibold uppercase tracking-wide flex items-center gap-1.5 ${tone}`}>{icon}{title}</h3>
      <ul className="space-y-1.5 text-sm text-foreground list-disc pl-5 marker:text-muted-foreground">
        {items.map((t, i) => <li key={i}>{t}</li>)}
      </ul>
    </div>
  );
}

// Claude's plain-language briefing on the dashboard for the chosen period. Generated only when asked.
export function AiFinanceSummary({ from, to, periodLabel, disabled }: { from: string; to: string; periodLabel: string; disabled?: boolean }) {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // A new period needs a new briefing.
  useEffect(() => { setSummary(null); setError(null); }, [from, to]);

  const run = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await aiService.summarizeFinance({ from: from || undefined, to: to || undefined });
      setSummary(res.data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not write the summary');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="border-primary/20">
      <CardHeader className="pb-3 flex flex-row items-start justify-between gap-3 space-y-0">
        <div>
          <CardTitle className="text-base flex items-center gap-2"><Sparkles className="w-4 h-4 text-primary" /> AI summary</CardTitle>
          <CardDescription>{summary ? `${periodLabel}: what stands out` : `A short briefing on the figures below (${periodLabel}), written by Claude.`}</CardDescription>
        </div>
        <Button variant="outline" size="sm" className="gap-1.5 shrink-0" onClick={run} disabled={loading || disabled}>
          {summary ? <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} /> : <Sparkles className="w-3.5 h-3.5 text-primary" />}
          {loading ? 'Writing…' : summary ? 'Refresh' : 'Summarize'}
        </Button>
      </CardHeader>
      {(loading || error || summary) && (
        <CardContent className="space-y-4">
          {loading && !summary && (
            <p className="text-sm text-muted-foreground flex items-center gap-2" aria-live="polite">
              <Sparkles className="w-4 h-4 text-primary animate-pulse" /> Reading spending, invoices and aging…
            </p>
          )}
          {error && (
            <p className="text-sm text-amber-800 flex items-start gap-2" role="alert"><AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />{error}</p>
          )}
          {summary && (
            <>
              <p className="text-sm sm:text-base font-medium text-foreground">{summary.headline}</p>
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
                <List icon={<TrendingUp className="w-3.5 h-3.5" />} title="Highlights" items={summary.highlights} tone="text-sky-700" />
                <List icon={<AlertTriangle className="w-3.5 h-3.5" />} title="Watch" items={summary.risks} tone="text-amber-700" />
                <List icon={<ArrowRight className="w-3.5 h-3.5" />} title="Next steps" items={summary.actions} tone="text-emerald-700" />
              </div>
              <p className="text-xs text-muted-foreground">Generated by Claude from this dashboard's figures. Check the numbers before acting on them.</p>
            </>
          )}
        </CardContent>
      )}
    </Card>
  );
}
